"""Explanation is wrong, read: the attribution tells a story the
score did not.

Stage 52 detour: the explanation is generated by the largest
coefficient, but the decision was driven by the largest contribution
- value times weight. When the two differ, the explanation is a
rationalization, and a user who checks it catches the difference.

Run:
    uv run python core/explanation_wrong.py
"""

from __future__ import annotations

# (feature, value, weight)
FEATURES = [
    ("price", 2.0, -0.040),
    ("category affinity", 0.9, 0.010),
    ("similar users bought", 0.3, 0.200),
]


def main() -> None:
    print("explanation is wrong, read (coefficient vs contribution):")
    contributions = [(name, value, weight, value * weight) for name, value, weight in FEATURES]
    for name, value, weight, contrib in contributions:
        print(f"  {name:<22} value {value:.1f} x weight {weight:+.3f} "
              f"= {contrib:+.4f}")
    by_coeff = max(contributions, key=lambda c: abs(c[2]))
    by_contrib = max(contributions, key=lambda c: abs(c[3]))
    print(f"\n  largest coefficient: {by_coeff[0]} (weight {by_coeff[2]:+.3f})")
    print(f"  largest contribution: {by_contrib[0]} (value x weight {by_contrib[3]:+.4f})")
    print("\nreading: the explanation says 'similar users bought' because")
    print("its coefficient is largest, but the price term moved the")
    print("score further. The user checks the claim against what they")
    print("see - the price - and the explanation fails. Attribution")
    print("must explain the contribution, not the coefficient.")


if __name__ == "__main__":
    main()
