import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYNC_DOCS_PATH = ROOT / "site" / "sync-docs.py"

SPEC = importlib.util.spec_from_file_location("sync_docs", SYNC_DOCS_PATH)
assert SPEC is not None and SPEC.loader is not None
SYNC_DOCS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SYNC_DOCS)


def test_relative_lesson_links_become_absolute_public_routes():
    source = Path("foundations/README.md")
    markdown = (
        "[loop](01-first-training-loop/) "
        "[training](../platform/training/README.md#next)"
    )

    rewritten = SYNC_DOCS.rewrite_links(markdown, source)

    assert "[loop](/playground/foundations/01-first-training-loop)" in rewritten
    assert "[training](/playground/platform/training#next)" in rewritten


def test_chapter_order_comes_from_the_manifest_not_the_directory_name():
    """The nav once read 02, 07, 06, 03 because positions were never emitted.

    Docusaurus sorts an autogenerated sidebar alphabetically by filename, so
    `platform/training/` sorted after `platform/serving/` no matter what the
    headings said. Position now comes from `standards/curriculum-order.txt`.
    """
    order = SYNC_DOCS.CHAPTER_ORDER

    assert order["platform/data"] < order["platform/training"]
    assert order["platform/training"] < order["platform/serving"]
    assert order["platform/serving"] < order["platform/evaluation-observability"]
    assert SYNC_DOCS.order_from(Path("platform/training/README.md")) == order[
        "platform/training"
    ]


def test_every_listed_chapter_exists():
    for path in SYNC_DOCS.CHAPTER_ORDER:
        assert (ROOT / path / "README.md").is_file(), (
            f"{path} is listed in standards/curriculum-order.txt but has no README.md"
        )


def test_every_chapter_directory_is_listed():
    """A chapter missing from the manifest would sort into the default bucket.

    That is the drift this file exists to prevent: content added without the
    table of contents noticing.
    """
    expected = set(SYNC_DOCS.CHAPTER_ORDER)
    for section in ("platform", "capabilities"):
        for readme in sorted((ROOT / section).rglob("README.md")):
            chapter = readme.parent.relative_to(ROOT).as_posix()
            if any(part in ("core", "prod", "runs") for part in Path(chapter).parts):
                continue
            if SYNC_DOCS.DIR_NUM_RE.match(readme.parent.name):
                continue  # a sub-lesson, ordered by its own directory prefix
            assert chapter in expected or chapter == "platform/safety-governance", (
                f"{chapter} has a README but is not in standards/curriculum-order.txt"
            )


def test_headings_do_not_carry_their_own_chapter_number():
    """Inserting a chapter must stay a one-line change.

    A hand-written "# 03 — Pretraining" makes every insertion an O(n) edit
    across headings and prose, with nothing failing when one is missed.
    """
    offenders = []
    for section in ("foundations", "platform", "capabilities", "missions"):
        for path in sorted((ROOT / section).rglob("*.md")):
            first = next(
                (ln for ln in path.read_text().splitlines() if ln.startswith("# ")), ""
            )
            # `# Stage 08 — Serving` is the same defect as `# 03 — Pretraining`
            # wearing a word in front of it, and it slipped past the first
            # version of this pattern.
            if re.match(r"^# (?:stage|chapter|part|lesson|step)?\s*\d+\s*[—–:-]\s", first, re.IGNORECASE):
                offenders.append(f"{path.relative_to(ROOT)}: {first}")
    assert not offenders, (
        "these headings hard-code a chapter number; the number is generated from "
        "standards/curriculum-order.txt:\n  " + "\n  ".join(offenders)
    )


def test_supporting_directories_are_named_and_sorted_below_lessons():
    # A bare lowercase "runs" or "prod" beside real chapters reads as a defect.
    for name in ("runs", "core", "prod"):
        label, position = SYNC_DOCS.DIR_OVERRIDES[name]
        assert label[0].isupper()
        assert position > SYNC_DOCS.DEFAULT_POSITION


def test_relative_source_links_stay_on_github():
    source = Path("missions/01-language-model-agent/01-tokenizer/README.md")
    markdown = "[implementation](core/bpe.py)"

    rewritten = SYNC_DOCS.rewrite_links(markdown, source)

    assert rewritten == (
        "[implementation](https://github.com/kleon1024/agi-playground/blob/main/"
        "missions/01-language-model-agent/01-tokenizer/core/bpe.py)"
    )


def test_section_index_lists_are_in_curriculum_order():
    """The platform index once read Data, Pretraining, Adaptation... only by
    accident, because every title began with its position ("02 — Data") and
    the listing sorted alphabetically. Dropping the visible numbers turned it
    into Adaptation, Data, Evaluation, Pretraining — alphabetical nonsense.
    """
    index = ROOT / "site" / "docs" / "platform" / "index.md"
    if not index.is_file():
        return  # site not synced in this environment
    listed = re.findall(r"^- \[[^\]]+\]\(([^)/]+)/\)$", index.read_text(), re.MULTILINE)
    positions = [
        SYNC_DOCS.order_from(Path("platform") / name / "README.md") for name in listed
    ]
    assert positions == sorted(positions), (
        "site/docs/platform/index.md is not in curriculum order:\n  "
        + "\n  ".join(f"{n} (position {p})" for n, p in zip(listed, positions))
    )


def test_titles_do_not_carry_a_generated_number():
    """Rendered titles are the heading alone.

    The generated prefix showed a curriculum-global position on a page that
    only listed one branch, so the platform index read "02, 03, 08, 09" plus
    one entry with no number at all.
    """
    for section in ("platform", "missions", "capabilities"):
        index = ROOT / "site" / "docs" / section / "index.md"
        if not index.is_file():
            continue
        assert not re.search(r"^- \[\d+ [—–-] ", index.read_text(), re.MULTILINE), (
            f"site/docs/{section}/index.md still renders a numbered title"
        )
