import importlib.util
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYNC_DOCS_PATH = ROOT / "site" / "sync-docs.py"

# Sections that hold learner-facing chapters. `reference/` is deliberately
# absent: it is the contributor surface, and routing a learner into it from a
# topic index would contradict what its own section intro says it is for.
SECTIONS_WITH_CHAPTERS = (
    "01-language-model",
    "02-personalized-discovery",
    "03-quantitative-research",
    "04-agentic-platform",
    "05-game-ai",
    "07-multimodal-generation",
    "08-bio-pharma-modeling",
    "09-autonomous-driving",
    "foundations",
)


def test_sections_match_the_documented_boundaries():
    """A fifth entry here publishes a section with no written boundary.

    `platform/` and `capabilities/` were each a second telling of a mission
    over the same lifecycle, and both were reachable from the sidebar before
    anyone could say what separated them from the sections beside them. The
    sections that remain each have a one-sentence boundary in AGENTS.md.
    """
    assert [name for name, _ in SYNC_DOCS.SECTIONS] == [
        "01-language-model",
        "02-personalized-discovery",
        "03-quantitative-research",
        "04-agentic-platform",
        "05-game-ai",
        "07-multimodal-generation",
        "08-bio-pharma-modeling",
        "09-autonomous-driving",
        "foundations",
        "reference",
    ]

SPEC = importlib.util.spec_from_file_location("sync_docs", SYNC_DOCS_PATH)
assert SPEC is not None and SPEC.loader is not None
SYNC_DOCS = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SYNC_DOCS)


def test_relative_lesson_links_become_absolute_public_routes():
    source = Path("foundations/README.md")
    markdown = (
        "[loop](01-first-training-loop/) "
        "[reference](../reference/README.md#next)"
    )

    rewritten = SYNC_DOCS.rewrite_links(markdown, source)

    assert "[loop](/playground/foundations/first-training-loop)" in rewritten
    assert "[reference](/playground/reference#next)" in rewritten


def test_chapter_order_comes_from_the_manifest_not_the_directory_name():
    """The nav once read 02, 07, 06, 03 because positions were never emitted.

    Docusaurus sorts an autogenerated sidebar alphabetically by filename, so
    `foundations/` sorted after `infra/` no matter what the headings said.
    Position now comes from `reference/standards/curriculum-order.txt`.
    """
    order = SYNC_DOCS.CHAPTER_ORDER

    assert order["01-language-model"] < order["foundations"]
    assert SYNC_DOCS.order_from(Path("foundations/README.md")) == order[
        "foundations"
    ]


def test_every_listed_chapter_exists():
    for path in SYNC_DOCS.CHAPTER_ORDER:
        assert (ROOT / path / "README.md").is_file() or (ROOT / f"{path}.md").is_file(), (
            f"{path} is listed in the content graph but has neither a README.md "
            "nor a loose page"
        )


def test_every_chapter_directory_is_listed():
    """A chapter missing from the manifest would sort into the default bucket.

    That is the drift this file exists to prevent: content added without the
    table of contents noticing.
    """
    expected = set(SYNC_DOCS.CHAPTER_ORDER)
    for section in ("foundations",):
        for readme in sorted((ROOT / section).glob("*/README.md")):
            chapter = readme.parent.relative_to(ROOT).as_posix()
            if SYNC_DOCS.DIR_NUM_RE.match(readme.parent.name):
                continue  # ordered by its own directory prefix
            assert chapter in expected, (
                f"{chapter} has a README but is not in reference/standards/curriculum-order.txt"
            )


def test_headings_do_not_carry_their_own_chapter_number():
    """Inserting a chapter must stay a one-line change.

    A hand-written "# 03 — Pretraining" makes every insertion an O(n) edit
    across headings and prose, with nothing failing when one is missed.
    """
    offenders = []
    for section in SECTIONS_WITH_CHAPTERS:
        for path in sorted((ROOT / section).rglob("*.md")):
            first = next(
                (ln for ln in path.read_text().splitlines() if ln.startswith("# ")), ""
            )
            # `# Stage 08 — Serving` is the same defect as `# 03 — Pretraining`
            # wearing a word in front of it, and it slipped past the first
            # version of this pattern.
            if re.match(r"^# (?:stage|chapter|part|lesson|step)?\s*\d+\s*[—–:-]\s", first, re.IGNORECASE):
                offenders.append(f"{path.relative_to(ROOT)}: {first}")
    assert not offenders, (
        "these headings hard-code a chapter number; the number is generated from "
        "reference/standards/curriculum-order.txt:\n  " + "\n  ".join(offenders)
    )


def test_supporting_directories_are_named_and_sorted_below_lessons():
    # A bare lowercase "runs" or "prod" beside real chapters reads as a defect.
    for name in ("runs", "core", "prod"):
        label, position = SYNC_DOCS.DIR_OVERRIDES[name]
        assert label[0].isupper()
        assert position > SYNC_DOCS.DEFAULT_POSITION


def test_relative_source_links_stay_on_github():
    source = Path("01-language-model/tokenizer/README.md")
    markdown = "[implementation](core/bpe.py)"

    rewritten = SYNC_DOCS.rewrite_links(markdown, source)

    assert rewritten == (
        "[implementation](https://github.com/kleon1024/agi-playground/blob/main/"
        "01-language-model/tokenizer/core/bpe.py)"
    )


def test_runs_entries_can_cite_their_own_raw_evidence():
    """A `runs/` entry links to the records behind it -- result rows, produced
    patches. Those are files to look at on GitHub, not routes on this site, and
    a suffix missing from the rewriter does not produce a wrong link, it breaks
    the build."""
    source = Path("04-agentic-platform/cheap-or-expensive/runs/entry.md")
    markdown = "[rows](results.jsonl) and [patches](patches.diff)"

    rewritten = SYNC_DOCS.rewrite_links(markdown, source)

    base = "https://github.com/kleon1024/agi-playground/blob/main"
    stage = "04-agentic-platform/cheap-or-expensive/runs"
    assert rewritten == (
        f"[rows]({base}/{stage}/results.jsonl) and [patches]({base}/{stage}/patches.diff)"
    )


def test_section_index_lists_are_in_curriculum_order():
    """A section index once read in order only by accident, because every
    title began with its position ("02 — Data") and the listing sorted
    alphabetically. Dropping the visible numbers turned it into alphabetical
    nonsense.
    """
    index = ROOT / "site" / "docs" / "foundations" / "index.md"
    if not index.is_file():
        return  # site not synced in this environment
    # No `$` anchor: each entry now carries its level and reading time after
    # the link. This test is about ordering, not about the line's shape.
    listed = re.findall(r"^- \[[^\]]+\]\(([^)/]+)/\)", index.read_text(), re.MULTILINE)
    positions = [
        SYNC_DOCS.order_from(Path("foundations") / name / "README.md") for name in listed
    ]
    assert positions == sorted(positions), (
        "site/docs/foundations/index.md is not in curriculum order:\n  "
        + "\n  ".join(f"{n} (position {p})" for n, p in zip(listed, positions))
    )


def test_titles_do_not_carry_a_generated_number():
    """Rendered titles are the heading alone.

    The generated prefix showed a curriculum-global position on a page that
    only listed one branch, so a section index read "02, 03, 08, 09" plus one
    entry with no number at all.
    """
    for section in SECTIONS_WITH_CHAPTERS:
        index = ROOT / "site" / "docs" / section / "index.md"
        if not index.is_file():
            continue
        assert not re.search(r"^- \[\d+ [—–-] ", index.read_text(), re.MULTILINE), (
            f"site/docs/{section}/index.md still renders a numbered title"
        )


def test_every_published_page_is_reachable_from_the_sidebar():
    """Navigation must not silently drop a page.

    Building the sidebar explicitly fixed the "Evidence, Evidence, Evidence"
    tree and lost something else: the builder recursed into directories only,
    so every `LANDSCAPE.md`, every standard, every research pass, and all three
    compute-lane guides were published, linked from prose, and unreachable from
    navigation. Only `runs/`, `core/`, and `prod/` are supposed to be
    off-tree — they are evidence and implementation, cited from the lesson that
    owns them.
    """
    import json

    sidebar_file = ROOT / "site" / "sidebars.generated.json"
    docs = ROOT / "site" / "docs"
    if not sidebar_file.is_file() or not docs.is_dir():
        return  # site not synced in this environment

    listed: set[str] = set()

    def walk(node) -> None:
        if isinstance(node, list):
            for item in node:
                walk(item)
            return
        if not isinstance(node, dict):
            return
        if node.get("type") == "doc":
            listed.add(node["id"])
        link = node.get("link") or {}
        if link.get("type") == "doc":
            listed.add(link["id"])
        for item in node.get("items", []):
            walk(item)

    walk(json.loads(sidebar_file.read_text()))

    def route(doc_id: str) -> str:
        return doc_id.removesuffix("/index")

    listed = {route(doc_id) for doc_id in listed}
    missing = []
    for page in sorted(docs.rglob("*.md*")):
        relative = page.relative_to(docs)
        if set(relative.parts) & SYNC_DOCS.UNLISTED_DIRS:
            continue
        doc_id = route(relative.with_suffix("").as_posix())
        if doc_id in ("index", *listed):
            continue
        missing.append(doc_id)

    assert not missing, "published but unreachable from the sidebar:\n  " + "\n  ".join(
        missing
    )


def test_no_published_page_is_an_orphan_in_prose():
    """Reachable from the sidebar is not the same as reached by a reader.

    The test above proves every page is listed in navigation. It passed while
    ten pages had no inbound link from any sentence anywhere -- seven
    `LANDSCAPE.md` tables, a branch index, and a sub-lesson --
    which meant a reader following the causal spine of the curriculum never
    learned they existed. The `LANDSCAPE.md` case was the sharpest: AGENTS.md
    requires each one to name two production alternatives, and not one chapter
    pointed at the table it was requiring.
    """
    sections = (*SECTIONS_WITH_CHAPTERS, "reference")
    pages = [
        page
        for section in sections
        for page in sorted((ROOT / section).rglob("*.md"))
        if not {"core", "prod", "runs", "cache"} & set(page.parts)
    ]

    def page_id(path: Path) -> str:
        if path.name == "README.md":
            return path.parent.relative_to(ROOT).as_posix()
        return path.relative_to(ROOT).with_suffix("").as_posix()

    ids = {page_id(p) for p in pages}
    # Root docs route into the sections and count as prose like any chapter.
    sources = pages + [ROOT / "README.md", ROOT / "AGENTS.md"]
    linked: set[str] = set()
    for source in sources:
        if not source.is_file():
            continue
        for target in re.findall(r"\]\((?!http|#)([^)#]+)", source.read_text()):
            old_dir = str(Path(SYNC_DOCS.old_location(source.relative_to(ROOT).as_posix())).parent)
            try:
                resolved = (ROOT / old_dir / target).resolve().relative_to(ROOT.resolve())
            except ValueError:
                continue  # points outside the repository
            text = resolved.as_posix().rstrip("/")
            text = (
                text[: -len("/README.md")]
                if text.endswith("/README.md")
                else text.removesuffix(".md")
            )
            for old, new in SYNC_DOCS.RENAMES.items():
                if text == old or text.startswith(old + "/"):
                    text = new + text[len(old):]
                    break
            if text != page_id(source):
                linked.add(text)

    orphans = sorted(ids - linked)
    assert not orphans, (
        "published but linked from no sentence in the repository; a page only "
        "the sidebar knows about is a page nobody reads:\n  " + "\n  ".join(orphans)
    )


def test_angle_brackets_survive_inline_code_verbatim():
    """MDX does not parse JSX inside a code span, so `<` there needs no escape.

    Escaping it anyway does not round-trip: markdown renders a code span's
    contents literally, entities included, so the reader sees the eight
    characters `&lt;` instead of a `<`. The SFT lesson's chat template shipped
    that way — in the chapter arguing the template is a learned convention
    rather than magic syntax, which is the worst possible place for it.
    """
    prose = "The bytes `<|im_start|>` mark a turn, and <1,000 lines is prose."

    escaped = SYNC_DOCS.escape_mdx(prose)

    assert "`<|im_start|>`" in escaped, "inline code must be left alone"
    assert "&lt;1,000" in escaped, "bare prose still needs escaping"
    assert "&lt;|im_start|" not in escaped


def test_fenced_and_inline_code_are_both_stepped_over():
    document = (
        "prose with <1,000 lines in it\n"
        "```python\n"
        "if a < b:  # a fence is untouched\n"
        "```\n"
        "trailing `a < b` span and a bare < here"
    )

    escaped = SYNC_DOCS.escape_mdx(document)

    assert "&lt;1,000" in escaped
    assert "if a < b:" in escaped
    assert "`a < b`" in escaped
    assert "a bare &lt; here" in escaped


def test_a_tag_shaped_token_in_prose_is_left_for_mdx_to_read_as_jsx():
    """`<` followed by a letter is deliberately not escaped.

    It is genuinely ambiguous — `<Widget />` in a lesson is a component the page
    means to render. The rule is therefore that a tag-shaped token in prose is
    treated as a tag, and anything that must appear literally goes in backticks.
    Documented because the escaping docstring used to claim `<UNK>` was covered
    here, and it never was.
    """
    assert SYNC_DOCS.escape_mdx("a bare <UNK> token") == "a bare <UNK> token"


def test_every_chapter_appears_in_at_least_one_topic():
    """`site/topics.mdx` is the only index that cuts across sections.

    The sidebar groups chapters by which section owns them, which answers
    "where does a new chapter belong" and not "where is the chapter about the
    thing I am stuck on". Read-by-topic answers the second question -- and it
    silently stopped answering it, because nothing enforced coverage: it was
    written when the repository ended at mission 04 and, by the time anyone
    checked, it named 62 of 129 chapters. Missions 05-09 and the whole of
    `infra/` were unfindable from any cross-cutting page.

    Section roots are exempt: they are the sidebar's own top-level entries and
    the topic page links into their chapters instead.
    """
    topics = (ROOT / "site" / "topics.mdx").read_text()
    linked = {
        route.strip("/")
        for route in re.findall(r"\(/playground/([^)]*?)\)", topics)
    }

    missing = []
    for section in SECTIONS_WITH_CHAPTERS:
        for readme in sorted((ROOT / section).rglob("README.md")):
            chapter = readme.parent.relative_to(ROOT)
            if set(chapter.parts) & SYNC_DOCS.UNLISTED_DIRS:
                continue
            route = chapter.as_posix()
            if route == section or route in linked:
                continue
            missing.append(route)

    assert not missing, (
        "published but named by no topic in site/topics.mdx:\n  "
        + "\n  ".join(missing)
    )


def test_read_by_topic_links_all_resolve_to_a_real_chapter():
    """A topic entry that points at nothing is worse than a missing one.

    The coverage test above only proves every chapter is named somewhere. It
    cannot catch a link to a route that was renamed or never existed, which is
    exactly what happens when a chapter directory is renumbered.
    """
    topics = (ROOT / "site" / "topics.mdx").read_text()
    broken = []
    for route in re.findall(r"\(/playground/([^)]+?)\)", topics):
        target = ROOT / route.strip("/")
        if (target / "README.md").is_file() or target.with_suffix(".md").is_file():
            continue
        broken.append(route)

    assert not broken, "site/topics.mdx points at routes that do not exist:\n  " + (
        "\n  ".join(broken)
    )


def test_only_a_lesson_carries_a_build_status_badge():
    """The sidebar badge marks the exception, not the rule.

    It used to append "· verified" to every backed chapter, which tagged 97 of
    129 entries with the same seven characters: a label that fires almost
    always discriminates nothing and costs every entry the width. Inverted, it
    marks drafts -- but only on a lesson. A section, branch, or mission index
    has no `runs/` because it never promised a measurement, and "Foundations ·
    draft" reads as though the whole section were unfinished.
    """
    assert SYNC_DOCS.is_lesson(Path("01-language-model/eval/eval-gates"))
    assert not SYNC_DOCS.is_lesson(Path("foundations"))
    assert not SYNC_DOCS.is_lesson(Path("01-language-model"))

    docs = ROOT / "site" / "docs"
    if not docs.is_dir():
        return  # site not synced in this environment

    badged = [
        page.relative_to(docs).as_posix()
        for page in sorted(docs.rglob("index.md*"))
        if "· draft" in page.read_text()[:400]
    ]
    for page in badged:
        chapter = Path(page).parent
        source = ROOT / chapter
        assert SYNC_DOCS.is_lesson(source), f"{page} is an index, not a lesson"
