import React from 'react';
import ProcessDiagram, { type ProcessStep } from './ProcessDiagram';

const STEPS: ProcessStep[] = [
  { id: 'sample', carries: 'G rollouts', label: 'Sample', owns: 'A group of G responses to the same prompt, generated by the current policy.', handoff: 'G sampled trajectories.' },
  { id: 'score', carries: 'G rewards', label: 'Score', owns: "A deterministic verifier scoring each rollout's outcome.", handoff: 'One reward per rollout.' },
  { id: 'advantage', carries: 'G advantages', label: 'Advantage', owns: 'Standardizing reward within the group: (reward - group mean) / group std.', handoff: 'A per-rollout advantage — zero for every rollout if the group’s rewards do not vary.' },
  { id: 'update', carries: 'new parameters', label: 'Update', owns: "The clipped-surrogate objective, bounding how far one update can push a good action's probability.", handoff: 'Updated policy parameters.' },
  { id: 'kl-check', carries: 'a bounded update', label: 'KL check', owns: 'A separate reference policy measuring drift from the pre-RL model.', handoff: 'A policy that moved toward higher reward without erasing the SFT policy underneath it.' },
];

export default function RLTrainingLoop(): React.ReactElement {
  return (
    <ProcessDiagram
      eyebrow="One GRPO update"
      question="Where does this loop stop producing a gradient at all?"
      steps={STEPS}
      loop="The loop samples again from the updated policy — but if every rollout in a group gets the same reward, the group's standard deviation is zero, the advantage is 0/0, and that group contributes no gradient. This is the condition stage 04 of the language-model system checks before spending any compute."
    />
  );
}
