/**
 * Collapsing a prediction vector into one number is the product strategy,
 * expressed as arithmetic.
 *
 * Fine-rank hands every item a vector — predicted engagement, predicted
 * satisfaction — and a slate needs one scalar per item to sort by. Move the
 * satisfaction weight below and the slate reorders with no model retrained:
 * the weight itself is the decision about what this platform optimizes for.
 * Switch to a multiplicative combination and an item that is highly
 * engaging but almost nobody's idea of satisfying collapses instead of
 * merely losing ground, because a product punishes a weak dimension far
 * harder than a sum does — additive treats objectives as substitutes,
 * multiplicative treats them as requirements.
 *
 * The sponsored item participates in the same arithmetic rather than a
 * separate ad-ranking pass: its expected revenue is converted into utility
 * at an explicit trade rate and compared against the slate directly. Every
 * ad displaces an organic result, so raising the trade rate high enough
 * shows exactly which organic item it outbids and what that item's lost
 * value was — the displacement cost, priced in the same units as everything
 * else on the page.
 *
 * All scores here are illustrative, generated by a seeded pseudo-random
 * source so the display is stable across renders — they stand in for a
 * calibrated fine-ranker's output, not a measured one.
 */
import React, { useMemo, useState } from 'react';

interface Archetype {
  name: string;
  engage: [number, number];
  satisfy: [number, number];
}

const ARCHETYPES: Archetype[] = [
  { name: 'reach-shaped', engage: [0.55, 0.9], satisfy: [0.04, 0.3] },
  { name: 'quality-shaped', engage: [0.12, 0.4], satisfy: [0.55, 0.92] },
  { name: 'balanced', engage: [0.32, 0.68], satisfy: [0.32, 0.68] },
];

interface Candidate {
  id: string;
  kind: 'organic' | 'ad';
  archetype: string;
  pEngage: number;
  pSatisfy: number;
  bid?: number;
  pClickAd?: number;
}

function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function buildCandidates(): Candidate[] {
  const rand = mulberry32(20260501);
  const span = (r: [number, number]) => r[0] + rand() * (r[1] - r[0]);
  const items: Candidate[] = [];
  for (let i = 0; i < 9; i++) {
    const a = ARCHETYPES[i % 3];
    items.push({
      id: `Item ${String.fromCharCode(65 + i)}`,
      kind: 'organic',
      archetype: a.name,
      pEngage: span(a.engage),
      pSatisfy: span(a.satisfy),
    });
  }
  // The ad is a fixed illustrative constant, not sampled — a bid is a
  // business input, not a predicted quantity.
  items.push({
    id: 'Sponsored item',
    kind: 'ad',
    archetype: 'ad',
    pEngage: 0,
    pSatisfy: 0,
    bid: 2.4,
    pClickAd: 0.18,
  });
  return items;
}

const TOP_K = 6;

function scoreOf(c: Candidate, satWeight: number, mode: 'additive' | 'multiplicative'): number {
  const wSat = satWeight / 100;
  const wEngage = 1 - wSat;
  if (mode === 'additive') {
    return wEngage * c.pEngage + wSat * c.pSatisfy;
  }
  // Multiplicative: weights become exponents. At weight 0 a dimension is
  // erased (anything^0 = 1); at weight 1 it is squared, so a near-zero score
  // on that dimension collapses the product — nothing else compensates.
  const expEngage = 2 * wEngage;
  const expSat = 2 * wSat;
  return Math.pow(Math.max(c.pEngage, 0.001), expEngage) * Math.pow(Math.max(c.pSatisfy, 0.001), expSat);
}

export default function ValueTree(): React.ReactElement {
  const candidates = useMemo(buildCandidates, []);
  const [satWeight, setSatWeight] = useState(50);
  const [mode, setMode] = useState<'additive' | 'multiplicative'>('additive');
  const [tradeRate, setTradeRate] = useState(0.35);

  const { slate, adInSlate, displaced, userValue, revenue } = useMemo(() => {
    const ad = candidates.find((c) => c.kind === 'ad')!;
    const organics = candidates.filter((c) => c.kind === 'organic');
    const organicScored = organics.map((c) => ({ c, score: scoreOf(c, satWeight, mode) }));
    const organicRanked = [...organicScored].sort((a, b) => b.score - a.score);

    const adUtility = tradeRate * (ad.bid! * ad.pClickAd!);
    const merged = [...organicRanked, { c: ad, score: adUtility }].sort((a, b) => b.score - a.score);
    const top = merged.slice(0, TOP_K);
    const hasAd = top.some((row) => row.c.kind === 'ad');

    const organicOnlyTop = organicRanked.slice(0, TOP_K);
    const bumped = hasAd
      ? organicOnlyTop.find((row) => !top.some((t) => t.c.id === row.c.id)) ?? null
      : null;

    return {
      slate: top,
      adInSlate: hasAd,
      displaced: bumped,
      userValue: top.filter((row) => row.c.kind === 'organic').reduce((sum, row) => sum + row.score, 0),
      revenue: hasAd ? ad.bid! * ad.pClickAd! : 0,
    };
  }, [candidates, satWeight, mode, tradeRate]);

  const maxScore = Math.max(...slate.map((row) => row.score), 0.001);

  return (
    <div className="learning-widget">
      <div style={{ display: 'flex', gap: '1.2rem', flexWrap: 'wrap', marginBottom: '0.9rem', alignItems: 'center' }}>
        <label style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          satisfaction weight <strong>{satWeight}</strong>
          <input
            type="range"
            min={0}
            max={100}
            value={satWeight}
            onChange={(e) => setSatWeight(Number(e.target.value))}
            style={{ width: 150 }}
            aria-label="Weight on satisfaction versus engagement"
          />
        </label>
        <label style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          combine
          <select value={mode} onChange={(e) => setMode(e.target.value as 'additive' | 'multiplicative')}>
            <option value="additive">additive</option>
            <option value="multiplicative">multiplicative</option>
          </select>
        </label>
        <label style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          ad trade rate <strong>{tradeRate.toFixed(2)}</strong>
          <input
            type="range"
            min={0}
            max={100}
            value={Math.round(tradeRate * 100)}
            onChange={(e) => setTradeRate(Number(e.target.value) / 100)}
            style={{ width: 150 }}
            aria-label="Utility credited per illustrative dollar of ad revenue"
          />
        </label>
      </div>

      <ol style={{ listStyle: 'none', margin: 0, padding: 0, display: 'grid', gap: '0.4rem' }}>
        {slate.map((row, i) => (
          <li
            key={row.c.id}
            style={{
              display: 'grid',
              gridTemplateColumns: '1.6rem minmax(7rem, 1fr) 4.5rem',
              alignItems: 'center',
              gap: '0.6rem',
            }}
          >
            <span style={{ fontSize: 'var(--type-xs)', opacity: 0.7 }}>{i + 1}</span>
            <span>
              {row.c.kind === 'ad' ? (
                <strong style={{ color: 'var(--brand-chart-warning)' }}>{row.c.id}</strong>
              ) : (
                <>
                  {row.c.id}{' '}
                  <span style={{ fontSize: 'var(--type-xs)', opacity: 0.6 }}>({row.c.archetype})</span>
                </>
              )}
              <div
                style={{
                  height: 8,
                  marginTop: 2,
                  borderRadius: 2,
                  width: `${Math.max(4, (row.score / maxScore) * 100)}%`,
                  background: row.c.kind === 'ad' ? 'var(--brand-chart-warning-fill)' : 'var(--brand-chart-action-fill)',
                  transition: 'width 200ms ease-out',
                }}
              />
            </span>
            <span style={{ fontSize: 'var(--type-xs)', textAlign: 'right', fontVariantNumeric: 'tabular-nums' }}>
              {row.score.toFixed(3)}
            </span>
          </li>
        ))}
      </ol>

      <div style={{ display: 'flex', gap: '1.4rem', flexWrap: 'wrap', fontSize: 'var(--type-sm)', marginTop: '0.9rem' }}>
        <span>
          user value in slate <strong>{userValue.toFixed(2)}</strong>
        </span>
        <span>
          ad revenue in slate <strong>${revenue.toFixed(2)}</strong>
        </span>
        <span style={{ color: adInSlate ? 'var(--brand-chart-warning)' : 'var(--brand-chart-positive)' }}>
          {adInSlate && displaced
            ? `displaces ${displaced.c.id}, worth ${displaced.score.toFixed(3)} in user value`
            : adInSlate
              ? 'ad enters without bumping this top-6 view'
              : 'no ad clears the bar at this trade rate'}
        </span>
      </div>

      <p style={{ fontSize: 'var(--type-sm)', opacity: 0.75, marginTop: '0.7rem' }}>
        Every number here is illustrative, standing in for a calibrated
        fine-ranker's output. Move the satisfaction weight and the slate
        reorders — that reordering is the product strategy, expressed as
        arithmetic. Switch to multiplicative and reach-shaped items collapse
        instead of merely losing ground, because a product cannot be rescued
        by one large factor the way a sum can. Raise the trade rate and the
        ad eventually outbids the weakest organic item at the cutoff — its
        lost value is exactly what the arithmetic charges the ad for its
        placement.
      </p>
    </div>
  );
}
